"""empty message

Revision ID: 9c3db4ddb8d2
Revises: 01a353239de9
Create Date: 2022-07-24 12:41:16.707214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c3db4ddb8d2"
down_revision = "01a353239de9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("completed", sa.Boolean(), nullable=True))
    op.execute("UPDATE todos SET completed = False where completed IS NULL;")
    op.alter_column("todos", "completed", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "completed")
    # ### end Alembic commands ###
